locale: "en-CA"
title: "Thesada Cloud Documentation"
description: Thesada Cloud Documentation
url: "https://thesada.cloud"
baseurl: "/" 
repository: "thesada/thesada-docs"

theme: jekyll-theme-minimal
